### ISSUE TITLE
Merge mode for dbclient

### ISSUE THREAD

**Issue by vesameskanen** [pelias/dbclient#18]
I recently created a fork where the ES client for Pelias can be run in a kind of 'merge' mode. In that mode, the client does not overwrite existing docs when their ids conflict with new incoming docs. Instead, the client performs a deep merge for the docs which match by id. We use this option when creating multi-lang documents from OpenAddresses data.

I wonder if such a merge mode is interesting in wider scope? I thought it might be better to ask first before stressing you with new pull requests :)

**Comment by orangejulius** [comment]
It could be an interesting feature. Eventually we want to be able to support incremental updates to Pelias, so that could possibly help.

One gotcha to watch out for: when updating Elasticsearch documents in Pelias, you have to manually set the `phrase` field from the `name` field. It looks like [this](https://gist.github.com/orangejulius/effaf7186e9e31d24d8aa45f4edca9fb#file-index-js-L81).

**Comment by easherma** [comment]
I like this idea.
